server:
  port: 7000
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411/ # zipkin server的请求地址
    discovery-client-enabled: false # 让nacos把它当成一个url，而不是当服务名
  sleuth:
    sampler:
      probability: 1.0 # 采样的百分比
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product_route # routeId, 默认为UUID
          uri: lb://service-product # lb 从nacos中获取服务信息，service-product是服务的名称
          order: 1 # 优先级，数字越小，优先级越高
          predicates: # 断言工厂
            - Path=/product-serv/**
          filters: # 过滤器
            - StripPrefix=1
        - id: order_route
          uri: lb://service-order
          order: 1
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1