server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://localhost:9411/ # zipkin server的请求地址
    discovery-client-enabled: false # 让nacos把它当成一个url，而不是当服务名
  sleuth:
    sampler:
      probability: 1.0 # 采样的百分比
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&userSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999 # 与控制台进行交流的端口，使用未曾使用到的端口即可
        dashboard: localhost:8090 # 指定控制台服务的地址
#      filter:
#        enabled: false # 关闭sentinel的commonFilter实例化

# 改变ribbon负载均衡策略
service-product:  # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # RoundRobinRule-轮询选择 RandomRule-随机选择 ZoneAvoidanceRule-复合判断性能及可用性选择
    # RetryRule-对选定的负载均衡策略机上重试机制 BestAvailableRule-选择最小并发请求的server
    # AvailabilityFilteringRule-过滤一直失败被标记的一集高并发的
    # WeightedResponseTimeRule-根据相应时间分配权重，权重越小，被选中的可能性越低

# 开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
